
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rifki fikri
 */
public class KonversiAngka extends javax.swing.JFrame {

    /**
     * Creates new form KonversiAngka
     */
    public KonversiAngka() {
        initComponents();
    }
    public String konversi (int angka){
        String[] huruf = {
          ""," Satu"," Dua" ," Tiga"," Empat" ," Lima"," Enam" ," Tujuh"," Delapan"," Sembilan"," Sepuluh" ," Sebelas"   
        };
        
        if (angka < 12){
            return huruf[angka];
        }
        if (angka >=12 && angka <= 19){
            return huruf[angka % 10] + " Belas";
        }
        if (angka >=20 && angka <= 99){
            return huruf[angka / 10] + " Puluh" + huruf[angka % 10];
        }
        if (angka >=100 && angka <= 199){
            return " Seratus"+ konversi(angka % 100);
        }
        if (angka >=200 && angka <= 999){
            return huruf[angka / 100] + " Ratus" + konversi(angka % 100);
        }
        if (angka >=1000 && angka <= 1999){
            return " Seribu" + konversi(angka % 1000);
        }
        if (angka >=2000 && angka <= 9999){
            return konversi(angka / 1000) + " Ribu" + konversi(angka % 1000);
        }
        return "-";
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1_282 = new javax.swing.JLabel();
        konversi_282 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2_282 = new javax.swing.JLabel();
        jLabel3_282 = new javax.swing.JLabel();
        textAngka_282 = new javax.swing.JTextField();
        textTerbilang_282 = new javax.swing.JTextField();
        keluar_282 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1_282.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel1_282.setText("Konversi Angka ke Terbilang");

        konversi_282.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        konversi_282.setText("Konversi");
        konversi_282.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konversi_282ActionPerformed(evt);
            }
        });

        jLabel2_282.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2_282.setText("Masukka Angka (max 4 digit)");

        jLabel3_282.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3_282.setText("Terbilang");

        textAngka_282.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAngka_282ActionPerformed(evt);
            }
        });

        textTerbilang_282.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTerbilang_282ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3_282)
                        .addGap(18, 18, 18)
                        .addComponent(textTerbilang_282))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2_282, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addComponent(textAngka_282, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2_282)
                    .addComponent(textAngka_282, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3_282)
                    .addComponent(textTerbilang_282, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        keluar_282.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        keluar_282.setText("Keluar");
        keluar_282.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluar_282ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel1_282, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(konversi_282)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(keluar_282)
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1_282)
                .addGap(37, 37, 37)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(konversi_282)
                    .addComponent(keluar_282))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void keluar_282ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluar_282ActionPerformed
       System.exit(1);
    }//GEN-LAST:event_keluar_282ActionPerformed

    private void textAngka_282ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAngka_282ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAngka_282ActionPerformed

    private void konversi_282ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konversi_282ActionPerformed
        int angka;
        String Terbilang;
        
        angka = Integer.parseInt(textAngka_282.getText());
        
        if (angka > 9999){
            JOptionPane.showMessageDialog(null, "input lebih dari 4 digit");
            return ;
        }
        Terbilang = konversi(angka);
        textTerbilang_282.setText(String.valueOf(Terbilang));
    }//GEN-LAST:event_konversi_282ActionPerformed

    private void textTerbilang_282ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTerbilang_282ActionPerformed
        
    }//GEN-LAST:event_textTerbilang_282ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonversiAngka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonversiAngka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonversiAngka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonversiAngka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonversiAngka().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1_282;
    private javax.swing.JLabel jLabel2_282;
    private javax.swing.JLabel jLabel3_282;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton keluar_282;
    private javax.swing.JButton konversi_282;
    private javax.swing.JTextField textAngka_282;
    private javax.swing.JTextField textTerbilang_282;
    // End of variables declaration//GEN-END:variables
}
